# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "quencher"
license = "MIT"
licenselink = "https://github.com/kamiquasi/quencher/blob/master/LICENSE.md"
description = "Hugo theme for quenching your thirst for documentation"
homepage = "https://kamiquasi.github.io/quencher"
repo = "https://github.com/kamiquasi/quencher"
tags = ["documentation","code","search"]
features = ["documentation","code","rendered snippets","search"]
min_version = 0.25

[author]
  name = "Luke Dary"
  homepage = "https://kamiquasi.github.io"
