extends: eslint:recommended
overrides:
  files: [ "src/scripts/javascripts/*.js"]
env:
  browser: true
  jasmine: true
  jquery: true
  serviceworker: true
  amd: true
  node: true
globals:
  $: true
  jQuery: true
  angular: true
  sendCustomEvent: true
  digitalData: true
  Drupal: true
  drupalSettings: true
  ActiveXObject: true
  Keycloak: true
  deparam: true
  FastClick: true
  DocumentTouch: true
  moment: true
  RHDPOSDownload: true
  Symbol: true
rules:
  no-extra-parens: 1
  curly:
    - 2
    - all
  dot-location:
    - 2
    - property
  dot-notation:
    - 1
    - allowKeywords: false
  eqeqeq: 2
  no-else-return: 2
  no-eq-null: 2
  no-eval: 1
  no-global-assign: 2
  no-implicit-coercion: 2
  no-loop-func: 1
  no-magic-numbers: 1
  no-multi-spaces: 2
  no-multi-str: 2
  no-return-assign: 2
  no-script-url: 2
  no-unmodified-loop-condition: 2
  no-unused-expressions: 2
  vars-on-top: 1
  wrap-iife: 1
  yoda: 1
  strict: 1
  no-unused-vars: 1
  array-bracket-spacing: 2
  block-spacing: 2
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: true
  comma-dangle: 2
  comma-spacing: 2
  comma-style: 2
  computed-property-spacing: 2
  func-call-spacing: 1
  indent: 2
  key-spacing: 1
  keyword-spacing: 1
  linebreak-style: 1
  max-len:
    - 1
    - code: 100
      ignoreComments: true
      ignoreTrailingComments: true
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  no-multiple-empty-lines: 1
  no-plusplus:
    - 2
    - allowForLoopAfterthoughts: true
  no-trailing-spaces: 2
  object-curly-spacing: 2
  semi-spacing: 2